export default ClassificationConfig = {
    'clothes': [
        {imgUrl: '../assest/neiku.png',title: '内裤'},
        {imgUrl: '../assest/neiyi.png',title: '内衣'},
        {imgUrl: '../assest/wazi.png',title: '袜子'},
        {imgUrl: '../assest/dayi.png',title: '大衣'},
        {imgUrl: '../assest/jiajufu.png',title: '家具服'},
        {imgUrl: '../assest/chenshan.png',title: '衬衫'},
        {imgUrl: '../assest/waitao.png',title: '外套'},
    ],
    'kitchen': [
        {imgUrl: '../assest/guo.png',title: '锅具'},
        {imgUrl: '../assest/chan.png',title: '刀铲'},
        {imgUrl: '../assest/chuju.png',title: '功能厨具'},
        {imgUrl: '../assest/canju.png',title: '餐具'},
        {imgUrl: '../assest/beihu.png',title: '杯壶'},
        {imgUrl: '../assest/chaju.png',title: '茶具'},
        {imgUrl: '../assest/qingjie.png',title: '厨房清洁'},
    ],
    'parts': [
        {imgUrl: '../assest/neiku.png',title: '内裤'},
        {imgUrl: '../assest/neiyi.png',title: '内衣'},
        {imgUrl: '../assest/wazi.png',title: '袜子'},
        {imgUrl: '../assest/dayi.png',title: '大衣'},
        {imgUrl: '../assest/jiajufu.png',title: '家具服'},
        {imgUrl: '../assest/chenshan.png',title: '衬衫'},
        {imgUrl: '../assest/waitao.png',title: '外套'},
    ],
    'household': [
        {imgUrl: '../assest/guo.png',title: '锅具'},
        {imgUrl: '../assest/chan.png',title: '刀铲'},
        {imgUrl: '../assest/chuju.png',title: '功能厨具'},
        {imgUrl: '../assest/canju.png',title: '餐具'},
        {imgUrl: '../assest/beihu.png',title: '杯壶'},
        {imgUrl: '../assest/chaju.png',title: '茶具'},
        {imgUrl: '../assest/qingjie.png',title: '厨房清洁'},
    ],
    'children': [
        {imgUrl: '../assest/neiku.png',title: '内裤'},
        {imgUrl: '../assest/neiyi.png',title: '内衣'},
        {imgUrl: '../assest/wazi.png',title: '袜子'},
        {imgUrl: '../assest/dayi.png',title: '大衣'},
        {imgUrl: '../assest/jiajufu.png',title: '家具服'},
        {imgUrl: '../assest/chenshan.png',title: '衬衫'},
        {imgUrl: '../assest/waitao.png',title: '外套'},
    ],
    'groceries': [
        {imgUrl: '../assest/guo.png',title: '锅具'},
        {imgUrl: '../assest/chan.png',title: '刀铲'},
        {imgUrl: '../assest/chuju.png',title: '功能厨具'},
        {imgUrl: '../assest/canju.png',title: '餐具'},
        {imgUrl: '../assest/beihu.png',title: '杯壶'},
        {imgUrl: '../assest/chaju.png',title: '茶具'},
        {imgUrl: '../assest/qingjie.png',title: '厨房清洁'},
    ],
    'food': [
        {imgUrl: '../assest/neiku.png',title: '内裤'},
        {imgUrl: '../assest/neiyi.png',title: '内衣'},
        {imgUrl: '../assest/wazi.png',title: '袜子'},
        {imgUrl: '../assest/dayi.png',title: '大衣'},
        {imgUrl: '../assest/jiajufu.png',title: '家具服'},
        {imgUrl: '../assest/chenshan.png',title: '衬衫'},
        {imgUrl: '../assest/waitao.png',title: '外套'},
    ],
    'interest': [
        {imgUrl: '../assest/guo.png',title: '锅具'},
        {imgUrl: '../assest/chan.png',title: '刀铲'},
        {imgUrl: '../assest/chuju.png',title: '功能厨具'},
        {imgUrl: '../assest/canju.png',title: '餐具'},
        {imgUrl: '../assest/beihu.png',title: '杯壶'},
        {imgUrl: '../assest/chaju.png',title: '茶具'},
        {imgUrl: '../assest/qingjie.png',title: '厨房清洁'},
    ],
    'brand': [
        {imgUrl: '../assest/neiku.png',title: '内裤'},
        {imgUrl: '../assest/neiyi.png',title: '内衣'},
        {imgUrl: '../assest/wazi.png',title: '袜子'},
        {imgUrl: '../assest/dayi.png',title: '大衣'},
        {imgUrl: '../assest/jiajufu.png',title: '家具服'},
        {imgUrl: '../assest/chenshan.png',title: '衬衫'},
        {imgUrl: '../assest/waitao.png',title: '外套'},
    ],
    'washCare': [
        {imgUrl: '../assest/guo.png',title: '锅具'},
        {imgUrl: '../assest/chan.png',title: '刀铲'},
        {imgUrl: '../assest/chuju.png',title: '功能厨具'},
        {imgUrl: '../assest/canju.png',title: '餐具'},
        {imgUrl: '../assest/beihu.png',title: '杯壶'},
        {imgUrl: '../assest/chaju.png',title: '茶具'},
        {imgUrl: '../assest/qingjie.png',title: '厨房清洁'},
    ],
}